### PR TITLE
Support dio v5

### PR DESCRIPTION
**Pull request by dmakwt**

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
Hey @dmakwt a previous pull request added support for v5.. is there anything else we can take from your PR?

**Comment by Carapacik** [comment]
Plz decrease version of dart to 2.15

**Comment by Milad-Akarie** [comment]
already did, it's back to   sdk: '>=2.12.0 <3.0.0'

**Comment by dmakwt** [comment]
Thanks @Milad-Akarie; just change homepage: from https://github.com/dmakwt/pretty_diox_logger  to your repo

**Comment by dmakwt** [comment]
شكرا 💐

**Comment by Milad-Akarie** [comment]
عفوا..

**Comment by Carapacik** [comment]
I can take care of this case

**Pull request closed without merging**
