### PR TITLE
Fix connectTimeout and receiveTimeout 

### PR DESCRIPTION
**Pull request by Carapacik**

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
@Carapacik Hey, what does that do?

**Comment by Carapacik** [comment]
Converting object to an encodable object failed: Instance of 'Duration'

**Comment by Carapacik** [comment]
IT fix this and add recommended lints

**Comment by Carapacik** [comment]
Because for dio 5 connectTimeout and receiveTimeout now Duration

**Comment by Milad-Akarie** [comment]
@Carapacik can you check the review tap so I can merge this?

**Comment by Carapacik** [comment]
Yes

**Comment by Milad-Akarie** [comment]
Why change this 
        `value = '"${value.toString().replaceAll(RegExp(r'(\r|\n)+'), " ")}"';`
to this
       ` value = '"${value.toString().replaceAll(RegExp(r'([\r\n])+'), " ")}"';`

**Comment by Carapacik** [comment]
image
[\r\n] same as \r|\n

**Comment by Carapacik** [comment]
Analyzer error

**Comment by Milad-Akarie** [comment]
I see, alright then.

**Comment by Milad-Akarie** [comment]
published to pub.dev

**Pull request merged**
